sudo: required
services:
  - docker

before_install:
  - docker build -t kp1116/react-test -f   ./client -f Dockerfile.dev ./client

script:
  - docker run -e CI=true kp1116/react-test npm test

after_success:
  - docker build -t kp1116/multi-client ./client
  - docker build -t kp1116/multi-nginx ./nginx
  - docker build -t kp1116/multi-server ./server
  - docker build -t kp1116/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push them to Docker hub
  - docker push kp1116/multi-client
  - docker push kp1116/multi-nginx
  - docker push kp1116/multi-server
  - docker push kp1116/multi-worker
